include:
  - board: nice_nano_v2
    shield: sofle_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    config: config/sofle_left.conf
  - board: nice_nano_v2
    shield: sofle_right
    config: config/sofle_right.conf
  - board: nice_nano_v2
    shield: settings_reset
