include:
  - board: nice_nano_v2
    shield: sofle_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONF_FILE="config/sofle.conf;config/sofle_left.conf"
    artifact-name: sofle_left_with_studio

  - board: nice_nano_v2
    shield: sofle_right
    cmake-args: -DCONF_FILE="config/sofle.conf;config/sofle_right.conf"
    artifact-name: sofle_right

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset
